### ISSUE TITLE
中英名词对照表

### ISSUE THREAD

**Issue by peng1999** [rustlang-cn/rustlang-cn#27]
考虑到本项目有大量的翻译文档，一个统一的中英名词对照表有助于统一风格，使文本易懂，是翻译质量的重要保障。但目前只能在 @KaiserY 的 [Rust Book 第一版](https://github.com/KaiserY/rust-book-chinese)中找到一个相当不完善的 Rust 中英名词对照表。我认为可以先创建若干个 issue 逐个讨论较难的名词翻译，然后将其固定下来，作为整个中文社区的建议翻译。
cc @krircc

**Comment by krircc** [comment]
@peng1999 非常同意，之前团队成员已经推出了[中英名词对照表](https://github.com/rustlang-cn/rustlang-cn/blob/master/docs/中英文词汇表.md)，另外此处已有一份较好些的词汇表，准备引入过来，在此基础进行讨论，大家觉得如何？@rustlang-cn/rustlang-cn

**Comment by peng1999** [comment]
现有的名词对照表还比较杂乱，处于不太可用的状态。我认为首先应把它分为两个部分：
1. 通用概念
   这部分翻译不需要讨论。如果是已经广泛使用的概念，则已经有通行的译法，如**抽象语法树**（abstract syntax tree）。如果是其他领域的专有名词，由翻译者酌情翻译（或不译），并在对照表中记录。一些常用且与日常英语接近的词，如 testing（测试）、asterisk（星号），我认为应直接删去不录。
2. Rust 特有的概念。
   这部分应单独列出并开 issue 讨论。

可以以近期进行的 nomicon 和 cargo book 的翻译活动为契机，在翻译和校对过程中补充对照表（特别是第二部分）。

**Comment by krircc** [comment]
@peng1999 赞同
