### ISSUE TITLE
统一翻译：「 Unsafe Rust 」

### ISSUE THREAD

**Issue by peng1999** [rustlang-cn/rustlang-cn#34]
# 目前存在的翻译
「不安全 Rust 」，「 Unsafe Rust 」（不译）

---
「 Safe Rust 」的翻译也有类似的问题。

**Comment by peng1999** [comment]
出于尽量多翻译的考虑，似乎「不安全 Rust 」更合适。

**Comment by krircc** [comment]
通常我没有翻译这个
